name: Triweekly Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * SUN,TUE,THU'

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - name: Install Python Dependencies
      run: python -m pip install -r requirements.txt

    - name: Get Date 
      id: get-date
      run: echo "TODAY_DATE=$(date "+%Y%m%d")" >> "$GITHUB_OUTPUT"

    - name: Get Data From Zendesk
      env:
        EMAIL: ${{ secrets.EMAIL }}
        TOKEN: ${{ secrets.TOKEN }}
        SUBDOMAIN: ${{ secrets.SUBDOMAIN }}
      run: |
        mkdir -p output
        python zendesk_csat.py ${{ steps.get-date.outputs.TODAY_DATE }}

    - name: Upload AWS
      env:
        EMAIL: ${{ secrets.EMAIL }}
        TOKEN: ${{ secrets.TOKEN }}
        SUBDOMAIN: ${{ secrets.SUBDOMAIN }}
        SECRET_NAME: ${{ secrets.SECRET_NAME }}
        REGION_NAME: ${{ secrets.REGION_NAME}}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_DB_HOST: ${{ secrets.AWS_DB_HOST }}
        AWS_DB_USER: ${{ secrets.AWS_DB_USER}}
      run: |
        python upload.py ${{ steps.get-date.outputs.TODAY_DATE }}